#!/bin/sh
set -e

# --- 1. Locate Laravel Project ---
# Find the 'artisan' file to locate the project root directory.
ARTISAN_FILE="$(find / -type f -name artisan 2>/dev/null | head -n1)"
if [ -z "$ARTISAN_FILE" ]; then
  echo "ERROR: Could not find Laravel 'artisan' file. Exiting."
  exit 1
fi
APP_DIR="$(dirname "$ARTISAN_FILE")"
cd "$APP_DIR"
echo "✅ Laravel project found at $APP_DIR"

# --- 2. Configure Environment (.env) ---
# Use the .env file from Render's secret files if it exists.
# Otherwise, create a .env file from individual environment variables.
if [ -f /etc/secrets/.env ]; then
  echo "Found secret file, copying to .env"
  cp /etc/secrets/.env "$APP_DIR/.env"
else
  echo "No secret file found. Building .env from environment variables."
  # Set default APP_URL if not provided
  : "${APP_URL:=https://cattr-app.onrender.com}"

  # Construct the DATABASE_URL for TiDB Serverless, which requires TLS.
  if [ -z "$DATABASE_URL" ]; then
    DATABASE_URL="mysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?ssl-mode=VERIFY_IDENTITY"
  fi

  cat > "$APP_DIR/.env" <<EOF
# --- Generated by start.sh ---
APP_NAME=Cattr
APP_ENV=production
APP_DEBUG=false
APP_KEY=${APP_KEY}
APP_URL=${APP_URL}

DATABASE_URL=${DATABASE_URL}

DB_CONNECTION=mysql
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_DATABASE=${DB_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

# Path to system CA certificates for TLS verification
MYSQL_ATTR_SSL_CA=${MYSQL_ATTR_SSL_CA:-/etc/ssl/certs/ca-certificates.crt}
EOF
fi
# Ensure the file has Unix line endings
sed -i 's/\r$//' "$APP_DIR/.env" || true

# --- 3. Enforce TLS for Database Connection ---
# Modify Laravel's database config to use the SSL CA certificate.
# This ensures PDO connects to TiDB using the required TLS encryption.
DBCFG="$APP_DIR/config/database.php"
if [ -f "$DBCFG" ] && ! grep -q "PDO::MYSQL_ATTR_SSL_CA" "$DBCFG"; then
  echo "Patching config/database.php to enforce TLS..."
  cp "$DBCFG" "$DBCFG.bak"
  awk '
    BEGIN{inmysql=0; hasopt=0}
    { print }
    $0 ~ /'\''mysql'\''[[:space:]]*=>[[:space:]]*\[/ { inmysql=1; next }
    inmysql==1 && $0 ~ /options[[:space:]]*=>/ { hasopt=1 }
    inmysql==1 && $0 ~ /\],[[:space:]]*$/ {
      if (hasopt==0) {
        print "            '\''options'\'' => extension_loaded('\''pdo_mysql'\'') ? array_filter([\n                PDO::MYSQL_ATTR_SSL_CA => env('\''MYSQL_ATTR_SSL_CA'\''),\n            ]) : [],"
      }
      inmysql=0
    }
  ' "$DBCFG" > "$DBCFG.tmp" && mv "$DBCFG.tmp" "$DBCFG"
  echo "✅ TLS configured."
fi

# --- 4. Skip Incompatible Migrations for TiDB ---
# TiDB Serverless does not support TRIGGERS, and one migration has a duplicate index.
# We find these migration files and rename them so Laravel's migrator skips them.
MIGRATIONS_DIR="$APP_DIR/database/migrations"
if [ -d "$MIGRATIONS_DIR" ]; then
  echo "Scanning for incompatible migrations..."

  # Find and disable migrations that use CREATE/DROP TRIGGER
  # BusyBox grep uses -r, not -R for recursion.
  TRIGGER_MIGS="$(grep -rilE 'CREATE[[:space:]]+TRIGGER|DROP[[:space:]]+TRIGGER' "$MIGRATIONS_DIR" || true)"
  if [ -n "$TRIGGER_MIGS" ]; then
    echo "Disabling TiDB-incompatible trigger migrations:"
    echo "$TRIGGER_MIGS" | while read -r f; do
      [ -f "$f" ] || continue
      echo "  -> Skipping $f"
      mv "$f" "$f.tidb-skipped"
    done
  fi

  # Find and disable the known problematic 'add_index' migration
  for f in "$MIGRATIONS_DIR"/*add_index*.php; do
    [ -f "$f" ] || continue
    echo "Disabling known duplicate-index migration:"
    echo "  -> Skipping $f"
    mv "$f" "$f.tidb-skipped"
  done
  echo "✅ Incompatible migrations disabled."
fi

# --- 5. Apply Application-Level Patches ---
# Fix for "Class 'App\Models\Rule' not found" error in a specific migration
RULE_MIGRATION_FILE="$MIGRATIONS_DIR/2018_09_27_100017_update_rules.php"
if [ -f "$RULE_MIGRATION_FILE" ]; then
    echo "Patching incorrect namespace in $RULE_MIGRATION_FILE..."
    # Replace the incorrect 'App\Models\Rule' with the correct 'App\Rule'
    sed -i 's/App\\Models\\Rule/App\\Rule/g' "$RULE_MIGRATION_FILE"
    echo "✅ Patch applied."
fi


# --- 6. Prepare and Launch Application ---
echo "Clearing caches..."
php artisan config:clear
php artisan route:clear
php artisan view:clear
php artisan cache:clear

echo "Running database migrations..."
php artisan migrate --force

echo "Seeding the database..."
php artisan db:seed --force

echo "🚀 Starting Cattr application server..."
php artisan serve --host 0.0.0.0 --port "$PORT"
